### ISSUE TITLE
Title bar buttons do not appear in Gnome 46

### ISSUE THREAD

**Issue by oscar503sv** [EliverLara/Space#1]
I'm using Fedora 40 with Gnome 46 and the title bar buttons are not appearing. But they do appear in legacy applications.

![Captura desde 2024-05-03 18-54-50](https://github.com/EliverLara/Space/assets/47469379/9c3a52cb-d312-4576-8c4d-2561a201190a)

![Captura desde 2024-05-03 18-58-25](https://github.com/EliverLara/Space/assets/47469379/63da89c0-4102-4525-9b3c-43c3e8bdff56)

**Comment by EliverLara** [comment]
Hi, could you please try using [this script](https://github.com/odziom91/libadwaita-theme-changer) in order to copy the needed `assets` folder to the right directory?

**Comment by oscar503sv** [comment]
Hello, you were right, that was my problem, it was solved.

thank you!
