### ISSUE TITLE
Bug/Missed Detail in Show Application Window

### ISSUE THREAD

**Issue by namaelsan** [EliverLara/Space#2]
Im using Pop os with gnome 42.9, i installed the theme with the script you linked in the themes gnome page. It seems like the background and the letters are both a dark color in the applications window(opened by pressing the show applications button in the dock). As seen here 
![image](https://github.com/EliverLara/Space/assets/51801844/130faee0-45b9-46cc-84a6-394d793a52bf)
 Feel free to let me know if this is a fault on my part if not please fix it. Thanks for reading.

**Comment by EliverLara** [comment]
Hi, which of the theme options are you using?

**Comment by namaelsan** [comment]
Hi im using the space-transperancy-adaptive option. but it seems like the problem persists with regular space-transparency aswell. Thanks for answering

**Comment by EliverLara** [comment]
There is no `space-transperancy-adaptive` option in this theme. However, Could you try renaming the theme folder and add `-dark` at the endof the name please?
