### ISSUE TITLE
Bug: Window controls not showing

### ISSUE THREAD

**Issue by luizlealdev** [EliverLara/Space#3]
I'm using Fedora 40, and when I applied the `Space-transparency` theme with `Colloid` icon theme, everything worked well, but the window controls aren't showing.

![Screenshot image](https://i.imgur.com/S3Ejhy7.png "Screenshot")
![Screenshot image](https://i.imgur.com/bkxDjlw.png "Screenshot")

**Comment by EliverLara** [comment]
Hi, Could you please try using [this script](https://github.com/odziom91/libadwaita-theme-changer)? since it copies the needed files to the right directories

**Comment by luizlealdev** [comment]
Thanks!

![Screenshot image](https://i.imgur.com/fqx5o6R.png "Screenshot")
